# Generated by Django 3.1.4 on 2021-01-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProduct',
        ),
    ]
