# Generated by Django 3.1.4 on 2021-08-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='alt',
            field=models.CharField(default='sl', max_length=250),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(default='p', max_length=200),
        ),
    ]
