# Generated by Django 3.1.4 on 2021-01-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_allproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllProduct',
            new_name='Products',
        ),
    ]
