# Generated by Django 3.1.4 on 2021-08-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210807_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
