# Generated by Django 3.1.4 on 2021-01-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_tecno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Tecno',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
