# Generated by Django 3.1.4 on 2021-01-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210112_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.AddField(
            model_name='products',
            name='img_url',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
