# Generated by Django 3.1.4 on 2021-01-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
    ]
