# Generated by Django 3.1.4 on 2021-01-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllProduct',
            new_name='Product',
        ),
    ]
